module.exports={
	pages:[
		["/","main@index"],
		["/aaa/bbbb","main@aabb"],
		["/aaa","main@aaaa"],
		["/bbb","main@bbbb"],
		["/bbb2","main@bbbb2"],
		["/bbb3","main@bbbb3"],
		["/ccc","aaa@yours"],
		["/ddd/{:id?}",{controller:"aaa",action:"whois"}],
		["/eee/{:id}/{:id2?}",{controller:"aaa",action:"e!"}],
		["/fff/{:id}/ggg/{:id2?}",{controller:"aaa",action:"e!"}]
	],
	error:{
		404:"notfound404",
	}
};