module.exports={
	pages:[
		["/","main@index"],
		["/aaa","main@aaaa"],
		["/bbb","main@bbbb"],
		["/ccc","aaa@yours"],
		["/ddd/{:id?}",{controller:"aaa",action:"whois"}]
	],
	error:{
		404:"notfound404",
	}
};